import asyncio
import inspect
import json
import os
import re
import time
from typing import Any, Dict, List, Optional, TypedDict

import asyncpg
from google import genai
from google.genai.errors import APIError, ClientError
from langgraph.graph import END, START, StateGraph
from llama_cpp import Llama, LlamaGrammar
from sentence_transformers import SentenceTransformer

from app.agent.database import (
    hybrid_search_fallback_async,
    query_medical_metrics_async,
)
from app.agent.grammar import JSON_GRAMMAR
from app.core.config import settings
from app.core.logging import logger


# 1. Model Loading and Gemini Client Initialization
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_PATH = os.path.join(BASE_DIR, "model", settings.LLM_MODEL_FILE)

if not os.path.exists(MODEL_PATH):
    logger.error("Cannot find model file! Verified path: %s", MODEL_PATH)
    raise FileNotFoundError(f"Cannot find model file! Verified path: {MODEL_PATH}")

logger.info("[Startup] Loading local fine-tuned LLM engine from: %s ...", MODEL_PATH)
llm = Llama(
    model_path=MODEL_PATH,
    n_ctx=2048,
    verbose=False
)

logger.info("[Startup] Loading SentenceTransformer embedding model (%s)...", settings.EMBEDDING_MODEL_NAME)
embed_model = SentenceTransformer(settings.EMBEDDING_MODEL_NAME)

# Load and configure Gemini Client
raw_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY") or ""
gemini_api_key = raw_key.strip().strip('"\'')
gemini_client = genai.Client(api_key=gemini_api_key) if gemini_api_key else None

llm_lock = asyncio.Lock()


# 2. Agentic State Machine Schema
class AgentState(TypedDict, total=False):
    clinical_text: str             # Raw input clinical note
    extracted_metrics: List[str]   # Medical metrics extracted by the fine-tuned LLM
    rag_data: Dict[str, Any]       # Reference ranges and clinical definitions from PostgreSQL
    clinical_synthesis: str        # Clinical synthesis generated by Gemini (Augmentation + Generation)
    final_analysis: Dict[str, Any] # Final comparative diagnostic report
    retry_count: int               # Number of self-correction attempts
    json_valid: bool               # Flag indicating whether output conforms to JSON schema
    is_correction: bool            # Flag indicating whether state machine is in self-correction loop
    db_pool: Optional[Any]         # AsyncPG connection pool instance


def is_potential_injection(text: str) -> bool:
    """Detect adversarial prompt injection attempts against the agentic workflow."""
    injection_patterns = [
        r"ignore current instruction",
        r"ignore the prompt",
        r"forget previous instruction",
        r"forget the above instruction", 
        r"system override",
        r"you are now an assistant",
        r"bypass restriction",          
        r"bypass guardrails"            
    ]
    text_lower = text.lower()
    for pattern in injection_patterns:
        if re.search(pattern, text_lower):
            return True
    return False


async def guardrail_node(state: AgentState) -> Dict[str, Any]:
    """Inspect clinical input against security guardrails and injection patterns."""
    text = state.get('clinical_text', '').strip()
    logger.info("[Node 0] Triggering input guardrail safety verification...")
    
    if is_potential_injection(text):
        logger.warning("[Node 0] [ALERT] Potential Prompt Injection detected! Aborting state machine execution immediately.")
        return {
            "extracted_metrics": [],
            "json_valid": False,
            "retry_count": 99,
            "is_correction": False
        }
        
    logger.info("[Node 0] Security check passed. Proceeding to entity extraction.")
    return {"is_correction": False}


async def extract_metrics_node(state: AgentState) -> Dict[str, Any]:
    """
    Extract clinical metrics using local fine-tuned Gemma model 
    with JSON grammar-constrained decoding.
    """
    text = state.get('clinical_text', '').strip()
    current_retry = state.get("retry_count", 0)
    is_correction = state.get("is_correction", False)
    
    if current_retry == 99:
        return {
            "extracted_metrics": [],
            "json_valid": True,
            "retry_count": 99,
            "is_correction": False
        }
    
    logger.info("[Node 1] Extracting medical metrics via Constrained Decoding... (Attempt #%d)", current_retry + 1)
    
    if len(text) < 4 or not re.search(r'[a-zA-Z0-9]', text):
        logger.info("[Node 1] Input text too short or invalid. Empty query assumed.")
        return {
            "extracted_metrics": [],
            "json_valid": True,
            "retry_count": current_retry + 1,
            "is_correction": False
        }

    temp = 0.3 if is_correction else 0.1
    instruction = "Extract valid medical metrics from the clinical text. Output JSON only."
    prompt = (
        "Below is an instruction that describes a task, paired with an input that provides further context. "
        "Write a response that appropriately completes the request.\n\n"
        f"### Instruction:\n{instruction}\n\n"
        f"### Input:\n{text}\n\n"
        "### Response:\n"
    )

    extracted = []
    json_valid = False

    try:
        start_time = time.time()
        async with llm_lock:
            response = await asyncio.to_thread(
                llm,
                prompt, 
                max_tokens=256, 
                stop=["\n\n", "###"],
                temperature=temp,
                grammar=JSON_GRAMMAR
            )
        latency = time.time() - start_time
        
        raw_text = response['choices'][0]['text'].strip()
        usage = response.get("usage", {})
        logger.info(
            "[Node 1] Inference Latency: %.4fs | Tokens: %s | Constrained Output: %s",
            latency,
            usage.get("total_tokens", "N/A"),
            raw_text
        )

        parsed = json.loads(raw_text)
        extracted = parsed.get("query", [])
        
        if isinstance(extracted, list):
            json_valid = True
            
        logger.info("[Node 1] Extracted Metrics: %s", extracted)
    except Exception as e:
        logger.error("[Node 1] Extraction/Parsing Failed: %s", e, exc_info=True)

    return {
        "extracted_metrics": extracted,
        "json_valid": json_valid,
        "retry_count": current_retry + 1,
        "is_correction": not json_valid
    }


def check_extraction_quality(state: AgentState) -> str:
    """Evaluate extraction validity to route to reflection loop or proceed to RAG stage."""
    retry_count = state.get("retry_count", 0)
    if retry_count == 99:
        return "continue_to_rag"
    if state.get("json_valid", False):
        return "continue_to_rag"
    if retry_count < 2:
        logger.warning("[LangGraph Reflection] Output invalid. Bouncing back to Node 1 for retry #%d...", retry_count + 1)
        return "retry_extraction"
    
    logger.warning("[LangGraph CircuitBreaker] Maximum retries reached. Forcing fallback pipeline.")
    return "continue_to_rag"


RRF_THRESHOLD = 0.0163


async def query_database_node(state: AgentState) -> Dict[str, Any]:
    """Execute two-tier retrieval: Exact SQL batch retrieval with Hybrid RRF vector fallback."""
    logger.info("[Node 2] Initiating PostgreSQL Relational RAG retrieval...")
    metrics = state.get("extracted_metrics", [])
    db_pool = state.get("db_pool")
    
    if not metrics:
        logger.info("[Node 2] No valid metrics extracted. Skipping RAG stage safely.")
        return {"rag_data": {}}
        
    logger.info("[Node 2] [Step 1] Exact batch querying for: %s", metrics)
    rag_results = await query_medical_metrics_async(metrics, db_pool)
    
    missing_metrics = [m for m in metrics if m not in rag_results]
    
    if missing_metrics and db_pool is not None:
        logger.info("[Node 2] [Step 2B] Triggering Hybrid Search Fallback for: %s", missing_metrics)
        for missing in missing_metrics:
            emb = await asyncio.to_thread(embed_model.encode, missing)
            embedding_list = emb.tolist()
            
            fallback_matches = await hybrid_search_fallback_async(
                query_text=missing,
                query_embedding=embedding_list,
                db_pool=db_pool,
                top_k=1
            )
            
            if fallback_matches:
                best = fallback_matches[0]
                label = best["metric_label"]
                rrf_score = best["rrf_score"]
                
                if rrf_score >= RRF_THRESHOLD:
                    logger.info("[Node 2] Hybrid Search Matched '%s' -> '%s' (RRF: %.4f >= %.4f)", missing, label, rrf_score, RRF_THRESHOLD)
                    rag_results[label] = {
                        "lower": best["lower"],
                        "upper": best["upper"],
                        "unit": best["unit"],
                        "definition": best["definition"],
                        "match_type": "hybrid_rrf",
                        "rrf_score": rrf_score
                    }
                else:
                    logger.info("[Node 2] Discarded weak match '%s' -> '%s' (RRF: %.4f < %.4f)", missing, label, rrf_score, RRF_THRESHOLD)

    if not rag_results:
        logger.info("[Node 2] No metrics found after exact & hybrid retrieval. RAG payload empty.")
    else:
        logger.info("[Node 2] RAG Fetch Completed: %s", list(rag_results.keys()))
        
    return {"rag_data": rag_results}


# 3. Augmentation & Generation Node (Dual-RAG Synthesis)

async def clinical_synthesis_node(state: AgentState) -> Dict[str, Any]:
    """
    Perform Context Augmentation and LLM Generation via Gemini
    with automated model fallback on rate limits (HTTP 429).
    """
    logger.info("[Node 3] Performing RAG Augmentation & Generation (Gemini Clinical Synthesis)...")
    clinical_text = state.get("clinical_text", "").strip()
    rag_data = state.get("rag_data", {})
    
    if not rag_data or not gemini_client:
        logger.info("[Node 3] No retrieved metrics or Gemini client not ready. Skipping clinical generation.")
        return {"clinical_synthesis": ""}

    # 1. Augmentation (assemble grounded reference context)
    metrics_benchmarks = []
    for name, info in rag_data.items():
        ref_range = f"{info.get('lower', 'N/A')} - {info.get('upper', 'N/A')} {info.get('unit', '')}"
        desc = info.get('definition', '')[:120]
        metrics_benchmarks.append(f"- {name}: Normal Range ({ref_range}), Clinical Role: {desc}")
    
    context_str = "\n".join(metrics_benchmarks)

    prompt = inspect.cleandoc(f"""
    You are an expert clinical decision support assistant. Explain why the following lab tests were ordered for this specific clinical case and provide concise diagnostic insights.

    ### CLINICAL CASE / NOTE:
    "{clinical_text}"

    ### RETRIEVED LAB BENCHMARKS & CONTEXT:
    {context_str}

    ### REQUIREMENTS:
    1. Explain the clinical correlation between the patient's symptoms (e.g. fever, acute presentation) and these specific lab metrics.
    2. Briefly mention key risks or what abnormal findings would indicate in this context.
    3. Keep the tone concise, objective, and professional (around 80-120 words).
    """)

    # 2. Generation (call Gemini API with fallback cascade on quota limits)
    candidate_models = ["gemini-2.5-flash", "gemini-1.5-flash", "gemini-1.5-pro"]
    synthesis_result = ""

    for model_name in candidate_models:
        try:
            response = await asyncio.to_thread(
                lambda m=model_name: gemini_client.models.generate_content(
                    model=m,
                    contents=prompt
                )
            )
            if response and response.text:
                synthesis_result = response.text.strip()
                logger.info("[Node 3] Successfully generated synthesis with %s.", model_name)
                break
        except (ClientError, APIError) as e:
            if "429" in str(e) or "RESOURCE_EXHAUSTED" in str(e):
                logger.warning("[Node 3] Model %s quota exhausted (429). Retrying next model...", model_name)
                continue
        except Exception as e:
            logger.error("[Node 3] Synthesis failed on %s: %s", model_name, e, exc_info=True)

    return {"clinical_synthesis": synthesis_result}


def analyze_and_compare_node(state: AgentState) -> Dict[str, Any]:
    """Assemble final diagnostic payload combining RAG evidence and AI clinical synthesis."""
    logger.info("[Node 4] Assembling final RAG + Agent structured report...")
    rag_data = state.get("rag_data", {})
    synthesis = state.get("clinical_synthesis", "")
    retry_count = state.get("retry_count", 1)
    
    status_str = "security_blocked" if retry_count == 99 else ("success" if rag_data else "no_metrics_found")
    
    analysis = {
        "status": status_str,
        "detected_metrics_count": len(rag_data),
        "clinical_synthesis": synthesis,  # Grounded clinical interpretation
        "metrics_reference": rag_data,
        "total_attempts_used": 0 if retry_count == 99 else retry_count
    }
    return {"final_analysis": analysis}


# 4. State Graph Compilation
workflow = StateGraph(AgentState)

workflow.add_node("guardrail", guardrail_node)
workflow.add_node("extract_metrics", extract_metrics_node)
workflow.add_node("query_database", query_database_node)
workflow.add_node("synthesis", clinical_synthesis_node)
workflow.add_node("analyze_compare", analyze_and_compare_node)

workflow.add_edge(START, "guardrail")
workflow.add_edge("guardrail", "extract_metrics")

workflow.add_conditional_edges(
    "extract_metrics",
    check_extraction_quality,
    {
        "retry_extraction": "extract_metrics",
        "continue_to_rag": "query_database" 
    }
)

# Sequential transition: query_database -> synthesis -> analyze_compare -> END
workflow.add_edge("query_database", "synthesis")
workflow.add_edge("synthesis", "analyze_compare")
workflow.add_edge("analyze_compare", END)

app = workflow.compile()